import { PrismaClient, LeadSource, JobStatus, TaskType, TaskStatus, Channel, PlanType } from "@prisma/client";
import bcrypt from "bcryptjs";
import { DEFAULT_TEMPLATES } from "../emails/defaults";

const prisma = new PrismaClient();

async function main() {
  const email = "demo@rebooker.io";
  const password = "demo1234";
  const hashedPassword = await bcrypt.hash(password, 10);

  // Reset demo user to keep seed idempotent.
  await prisma.user.deleteMany({ where: { email } });

  const user = await prisma.user.create({
    data: {
      email,
      name: "Alex Demo",
      ownerName: "Alex",
      hashedPassword,
      subscription: {
        create: { plan: PlanType.FREE },
      },
      templates: {
        create: DEFAULT_TEMPLATES.map((t) => ({
          type: t.type,
          name: t.name,
          subject: t.subject,
          body: t.body,
          isDefault: true,
        })),
      },
    },
  });

  // 5 contacts
  const contactSeed = [
    { fullName: "Maria Popescu", phone: "+40 722 111 222", email: "maria.popescu@example.com", companyName: null, serviceType: "Auto detailing", source: LeadSource.REFERRAL, notes: "Owns a black Audi Q5" },
    { fullName: "John Smith", phone: "+1 415 555 0144", email: "john@smithplumbing.example", companyName: "Smith Plumbing", serviceType: "Plumbing", source: LeadSource.WEBSITE, notes: "Leaky kitchen sink" },
    { fullName: "Elena García", phone: "+34 600 777 888", email: "elena.garcia@example.com", companyName: null, serviceType: "House cleaning", source: LeadSource.PHONE, notes: "Bi-weekly deep clean" },
    { fullName: "Tom Becker", phone: "+49 170 1234567", email: "tom.becker@example.com", companyName: "Becker GmbH", serviceType: "Electrical", source: LeadSource.WHATSAPP, notes: "Office rewiring estimate" },
    { fullName: "Sara Lee", phone: "+1 212 555 0198", email: "sara.lee@example.com", companyName: null, serviceType: "Gardening", source: LeadSource.MANUAL, notes: "Monthly hedge trimming" },
  ];

  const contacts = await Promise.all(
    contactSeed.map((c) =>
      prisma.contact.create({ data: { ...c, userId: user.id } })
    )
  );

  const now = new Date();
  const plusDays = (n: number) => new Date(now.getTime() + n * 86400000);
  const minusDays = (n: number) => new Date(now.getTime() - n * 86400000);

  // 5 jobs in mixed statuses
  const jobsData = [
    { contactId: contacts[0].id, title: "Full detailing — Audi Q5", description: "Exterior + interior full detail", estimatedValue: "350.00", status: JobStatus.QUOTED, quoteSentAt: minusDays(3) },
    { contactId: contacts[1].id, title: "Kitchen sink repair", description: "Replace pipe + faucet", estimatedValue: "220.00", status: JobStatus.WON, quoteSentAt: minusDays(5), wonAt: minusDays(1) },
    { contactId: contacts[2].id, title: "Deep cleaning — 2BR apartment", description: "4 hour deep clean", estimatedValue: "180.00", status: JobStatus.COMPLETED, quoteSentAt: minusDays(10), wonAt: minusDays(7), completedAt: minusDays(2) },
    { contactId: contacts[3].id, title: "Office rewiring estimate", description: "On-site estimate required", estimatedValue: "1200.00", status: JobStatus.NEW },
    { contactId: contacts[4].id, title: "Hedge trimming — April", description: "Monthly service", estimatedValue: "90.00", status: JobStatus.LOST, lostAt: minusDays(4) },
  ];

  const jobs = await Promise.all(
    jobsData.map((j) =>
      prisma.job.create({
        data: {
          ...j,
          estimatedValue: j.estimatedValue,
          userId: user.id,
        },
      })
    )
  );

  // 6-8 tasks — mixed auto-generated and manual, some overdue
  await prisma.followUpTask.createMany({
    data: [
      // Overdue quote follow-up on the quoted Audi detailing job
      {
        userId: user.id,
        contactId: contacts[0].id,
        jobId: jobs[0].id,
        type: TaskType.QUOTE_FOLLOW_UP,
        title: "Follow up on quote",
        messagePreview: "Checking in on your quote",
        dueDate: minusDays(1),
        status: TaskStatus.PENDING,
        channel: Channel.EMAIL,
        autoGenerated: true,
      },
      // Confirmation due today
      {
        userId: user.id,
        contactId: contacts[1].id,
        jobId: jobs[1].id,
        type: TaskType.CONFIRMATION,
        title: "Send confirmation email",
        messagePreview: "Confirming your booking",
        dueDate: now,
        status: TaskStatus.PENDING,
        channel: Channel.EMAIL,
        autoGenerated: true,
      },
      // Review request due tomorrow
      {
        userId: user.id,
        contactId: contacts[2].id,
        jobId: jobs[2].id,
        type: TaskType.REVIEW_REQUEST,
        title: "Ask for a review",
        messagePreview: "Quick favor — would you leave us a review?",
        dueDate: plusDays(1),
        status: TaskStatus.PENDING,
        channel: Channel.EMAIL,
        autoGenerated: true,
      },
      // Manual task — call Tom about estimate
      {
        userId: user.id,
        contactId: contacts[3].id,
        jobId: jobs[3].id,
        type: TaskType.MANUAL,
        title: "Call Tom to schedule site visit",
        messagePreview: null,
        dueDate: plusDays(2),
        status: TaskStatus.PENDING,
        channel: Channel.MANUAL,
        autoGenerated: false,
      },
      // Reactivation for Sara
      {
        userId: user.id,
        contactId: contacts[4].id,
        type: TaskType.REACTIVATION,
        title: "Re-engage Sara — monthly hedge trim",
        messagePreview: "It's been a while",
        dueDate: plusDays(5),
        status: TaskStatus.PENDING,
        channel: Channel.EMAIL,
        autoGenerated: false,
      },
      // Already done task (review completed)
      {
        userId: user.id,
        contactId: contacts[2].id,
        jobId: jobs[2].id,
        type: TaskType.CONFIRMATION,
        title: "Send confirmation email",
        messagePreview: "Confirming your booking",
        dueDate: minusDays(7),
        status: TaskStatus.SENT,
        channel: Channel.EMAIL,
        autoGenerated: true,
        completedAt: minusDays(7),
      },
      // Another overdue manual task
      {
        userId: user.id,
        contactId: contacts[0].id,
        type: TaskType.MANUAL,
        title: "Text Maria about preferred date",
        messagePreview: null,
        dueDate: minusDays(2),
        status: TaskStatus.PENDING,
        channel: Channel.MANUAL,
        autoGenerated: false,
      },
    ],
  });

  console.log(`Seed complete. Login: ${email} / ${password}`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
