/**
 * Follow-Up Automation Engine
 *
 * This is the heart of the product. Keep all auto-generation rules here so
 * behavior stays consistent and easy to reason about.
 *
 * Rules:
 *  - QUOTED    → set quoteSentAt; create QUOTE_FOLLOW_UP task (due +2 days)
 *  - WON       → set wonAt; create CONFIRMATION task (due now)
 *  - COMPLETED → set completedAt; create REVIEW_REQUEST task (due +1 day)
 *  - LOST      → set lostAt; no task
 *  - NEW / REVIEW_REQUESTED → no-op (transition only)
 *
 * Overdue is computed at read time (PENDING + dueDate < now).
 */

import type { PrismaClient, Job, JobStatus } from "@prisma/client";
import { Channel, TaskStatus, TaskType } from "@prisma/client";

type Tx = Omit<
  PrismaClient,
  "$connect" | "$disconnect" | "$on" | "$transaction" | "$use" | "$extends"
>;

const DAY = 86400000;

export async function onJobStatusChange(
  tx: Tx,
  job: Job,
  newStatus: JobStatus
): Promise<Job> {
  const now = new Date();

  let updated: Job = job;

  switch (newStatus) {
    case "QUOTED": {
      updated = await tx.job.update({
        where: { id: job.id },
        data: {
          status: "QUOTED",
          quoteSentAt: job.quoteSentAt ?? now,
        },
      });
      await tx.followUpTask.create({
        data: {
          userId: job.userId,
          contactId: job.contactId,
          jobId: job.id,
          type: TaskType.QUOTE_FOLLOW_UP,
          title: "Follow up on quote",
          messagePreview: "Check in on the quote you sent",
          dueDate: new Date(now.getTime() + 2 * DAY),
          status: TaskStatus.PENDING,
          channel: Channel.EMAIL,
          autoGenerated: true,
        },
      });
      break;
    }
    case "WON": {
      updated = await tx.job.update({
        where: { id: job.id },
        data: { status: "WON", wonAt: now },
      });
      await tx.followUpTask.create({
        data: {
          userId: job.userId,
          contactId: job.contactId,
          jobId: job.id,
          type: TaskType.CONFIRMATION,
          title: "Send confirmation email",
          messagePreview: "Confirm the booking with the customer",
          dueDate: now,
          status: TaskStatus.PENDING,
          channel: Channel.EMAIL,
          autoGenerated: true,
        },
      });
      break;
    }
    case "COMPLETED": {
      updated = await tx.job.update({
        where: { id: job.id },
        data: { status: "COMPLETED", completedAt: now },
      });
      await tx.followUpTask.create({
        data: {
          userId: job.userId,
          contactId: job.contactId,
          jobId: job.id,
          type: TaskType.REVIEW_REQUEST,
          title: "Ask for a review",
          messagePreview: "Request a review from the customer",
          dueDate: new Date(now.getTime() + 1 * DAY),
          status: TaskStatus.PENDING,
          channel: Channel.EMAIL,
          autoGenerated: true,
        },
      });
      break;
    }
    case "LOST": {
      updated = await tx.job.update({
        where: { id: job.id },
        data: { status: "LOST", lostAt: now },
      });
      break;
    }
    case "REVIEW_REQUESTED":
    case "NEW":
    default: {
      updated = await tx.job.update({
        where: { id: job.id },
        data: { status: newStatus },
      });
      break;
    }
  }

  return updated;
}
