/**
 * Follow-Up Automation Engine
 *
 * Single source of truth for auto-generated tasks and contact lifecycle state.
 *
 * Rules:
 *  - QUOTED          → set quoteSentAt; create QUOTE_FOLLOW_UP task (+quoteFollowUpDays)
 *  - WON             → set wonAt; create CONFIRMATION task (due now)
 *  - COMPLETED       → set completedAt; create REVIEW_REQUEST task (+reviewRequestDays)
 *  - LOST            → set lostAt; no task
 *  - REVIEW_REQUESTED / NEW → status update only
 *
 * Contact status is derived and persisted after every job transition.
 * Overdue is computed at read time (PENDING + dueDate < now).
 */

import type { PrismaClient, Job, JobStatus } from "@prisma/client";
import { Channel, ContactStatus, TaskStatus, TaskType } from "@prisma/client";
import { log } from "@/lib/logger";

type Tx = Omit<
  PrismaClient,
  "$connect" | "$disconnect" | "$on" | "$transaction" | "$use" | "$extends"
>;

const DAY = 86400000;

export function deriveContactStatusFromJobs(jobStatuses: JobStatus[]): ContactStatus {
  if (jobStatuses.length === 0) return ContactStatus.LEAD;
  if (jobStatuses.some((s) => s === "WON")) return ContactStatus.WON;
  if (jobStatuses.some((s) => s === "NEW" || s === "QUOTED")) return ContactStatus.ACTIVE;
  if (jobStatuses.some((s) => s === "COMPLETED" || s === "REVIEW_REQUESTED")) return ContactStatus.COMPLETED;
  return ContactStatus.LOST;
}

export async function recalculateContactStatus(
  tx: Tx,
  contactId: string,
  extra?: Partial<{ lastContactedAt: Date }>
): Promise<ContactStatus> {
  const jobs = await tx.job.findMany({
    where: { contactId },
    select: { status: true },
  });
  const newStatus = deriveContactStatusFromJobs(jobs.map((j) => j.status));
  await tx.contact.update({
    where: { id: contactId },
    data: { status: newStatus, ...extra },
  });
  return newStatus;
}

export async function onJobStatusChange(
  tx: Tx,
  job: Job,
  newStatus: JobStatus
): Promise<Job> {
  const now = new Date();

  // Fetch user settings for configurable delays
  const user = await tx.user.findUnique({
    where: { id: job.userId },
    select: { quoteFollowUpDays: true, reviewRequestDays: true },
  });
  const quoteFollowUpDays = user?.quoteFollowUpDays ?? 2;
  const reviewRequestDays = user?.reviewRequestDays ?? 1;

  log("automation", "job_status_change", { jobId: job.id, from: job.status, to: newStatus });

  let updated: Job = job;

  switch (newStatus) {
    case "QUOTED": {
      updated = await tx.job.update({
        where: { id: job.id },
        data: {
          status: "QUOTED",
          quoteSentAt: job.quoteSentAt ?? now,
        },
      });
      await tx.followUpTask.create({
        data: {
          userId: job.userId,
          contactId: job.contactId,
          jobId: job.id,
          type: TaskType.QUOTE_FOLLOW_UP,
          title: "Follow up on quote",
          messagePreview: "Check in on the quote you sent",
          dueDate: new Date(now.getTime() + quoteFollowUpDays * DAY),
          status: TaskStatus.PENDING,
          channel: Channel.EMAIL,
          autoGenerated: true,
        },
      });
      break;
    }
    case "WON": {
      updated = await tx.job.update({
        where: { id: job.id },
        data: { status: "WON", wonAt: now },
      });
      await tx.followUpTask.create({
        data: {
          userId: job.userId,
          contactId: job.contactId,
          jobId: job.id,
          type: TaskType.CONFIRMATION,
          title: "Send confirmation email",
          messagePreview: "Confirm the booking with the customer",
          dueDate: now,
          status: TaskStatus.PENDING,
          channel: Channel.EMAIL,
          autoGenerated: true,
        },
      });
      break;
    }
    case "COMPLETED": {
      updated = await tx.job.update({
        where: { id: job.id },
        data: { status: "COMPLETED", completedAt: now },
      });
      await tx.followUpTask.create({
        data: {
          userId: job.userId,
          contactId: job.contactId,
          jobId: job.id,
          type: TaskType.REVIEW_REQUEST,
          title: "Ask for a review",
          messagePreview: "Request a review from the customer",
          dueDate: new Date(now.getTime() + reviewRequestDays * DAY),
          status: TaskStatus.PENDING,
          channel: Channel.EMAIL,
          autoGenerated: true,
        },
      });
      break;
    }
    case "LOST": {
      updated = await tx.job.update({
        where: { id: job.id },
        data: { status: "LOST", lostAt: now },
      });
      break;
    }
    case "REVIEW_REQUESTED":
    case "NEW":
    default: {
      updated = await tx.job.update({
        where: { id: job.id },
        data: { status: newStatus },
      });
      break;
    }
  }

  const newContactStatus = await recalculateContactStatus(tx, job.contactId, { lastContactedAt: now });
  log("automation", "contact_status_updated", { contactId: job.contactId, status: newContactStatus });

  return updated;
}
