"use server";

import { revalidatePath } from "next/cache";
import { prisma } from "@/lib/db";
import { requireUser } from "@/lib/auth";
import { contactSchema } from "@/lib/validators";
import { assertCanCreateContact, PlanLimitError } from "@/lib/plan-limits";
import { setMilestoneOnce } from "@/lib/activation";
import { log } from "@/lib/logger";
import { getDictionary, getLocale } from "@/lib/i18n";

type ActionResult = { ok: true; id?: string } | { ok: false; error: string };

function clean<T extends Record<string, unknown>>(obj: T): T {
  const out: Record<string, unknown> = {};
  for (const [k, v] of Object.entries(obj)) {
    out[k] = v === "" ? null : v;
  }
  return out as T;
}

export async function createContact(formData: FormData): Promise<ActionResult> {
  const user = await requireUser();
  const parsed = contactSchema.safeParse(Object.fromEntries(formData));
  if (!parsed.success) {
    return { ok: false, error: parsed.error.errors[0]?.message ?? "Invalid input" };
  }

  const data = clean(parsed.data);
  let contact: { id: string };
  try {
    contact = await prisma.$transaction(async (tx) => {
      await assertCanCreateContact(user.id, tx);
      return tx.contact.create({ data: { ...data, userId: user.id } });
    });
  } catch (err) {
    if (err instanceof PlanLimitError) {
      const t = getDictionary(getLocale());
      return { ok: false, error: t.planLimits[err.code] };
    }
    throw err;
  }

  await setMilestoneOnce(user.id, "firstContactCreatedAt", new Date()).catch(() => {});

  revalidatePath("/contacts");
  revalidatePath("/dashboard");
  return { ok: true, id: contact.id };
}

export async function updateContact(
  id: string,
  formData: FormData
): Promise<ActionResult> {
  const user = await requireUser();
  const parsed = contactSchema.safeParse(Object.fromEntries(formData));
  if (!parsed.success) {
    return { ok: false, error: parsed.error.errors[0]?.message ?? "Invalid input" };
  }

  const existing = await prisma.contact.findFirst({
    where: { id, userId: user.id },
    select: { id: true },
  });
  if (!existing) return { ok: false, error: "Contact not found" };

  await prisma.contact.update({
    where: { id },
    data: clean(parsed.data),
  });

  revalidatePath("/contacts");
  revalidatePath(`/contacts/${id}`);
  revalidatePath("/dashboard");
  return { ok: true, id };
}

export async function deleteContact(id: string): Promise<ActionResult> {
  const user = await requireUser();
  const existing = await prisma.contact.findFirst({
    where: { id, userId: user.id },
    select: { id: true },
  });
  if (!existing) return { ok: false, error: "Contact not found" };

  await prisma.contact.delete({ where: { id } });
  revalidatePath("/contacts");
  revalidatePath("/dashboard");
  return { ok: true };
}

export async function reactivateContact(contactId: string): Promise<ActionResult> {
  const user = await requireUser();
  const contact = await prisma.contact.findFirst({
    where: { id: contactId, userId: user.id },
    select: { id: true },
  });
  if (!contact) return { ok: false, error: "Contact not found" };

  const now = new Date();
  const t = getDictionary(getLocale());
  await prisma.$transaction(async (tx) => {
    await tx.contact.update({
      where: { id: contactId },
      data: { status: "LEAD", nextActionAt: now, lastContactedAt: now },
    });
    await tx.followUpTask.create({
      data: {
        userId: user.id,
        contactId,
        type: "REACTIVATION",
        title: t.contacts.reactivateTaskTitle,
        messagePreview: t.contacts.reactivateTaskPreview,
        dueDate: now,
        status: "PENDING",
        channel: "MANUAL",
        autoGenerated: true,
      },
    });
  });

  log("contacts", "contact_reactivated", { contactId, userId: user.id });

  revalidatePath(`/contacts/${contactId}`);
  revalidatePath("/contacts");
  revalidatePath("/followups");
  revalidatePath("/dashboard");
  return { ok: true };
}
