"use server";

import { revalidatePath } from "next/cache";
import { prisma } from "@/lib/db";
import { requireUser } from "@/lib/auth";
import { taskSchema, taskStatusSchema, sendEmailSchema } from "@/lib/validators";
import { assertCanCreateTask, PlanLimitError } from "@/lib/plan-limits";
import { setMilestoneOnce } from "@/lib/activation";
import { sendEmail } from "@/lib/email";
import { Channel, TaskStatus } from "@prisma/client";

type ActionResult = { ok: true; id?: string } | { ok: false; error: string };

export async function createTask(formData: FormData): Promise<ActionResult> {
  const user = await requireUser();
  const parsed = taskSchema.safeParse(Object.fromEntries(formData));
  if (!parsed.success) {
    return { ok: false, error: parsed.error.errors[0]?.message ?? "Invalid input" };
  }
  const data = parsed.data;

  const contact = await prisma.contact.findFirst({
    where: { id: data.contactId, userId: user.id },
    select: { id: true },
  });
  if (!contact) return { ok: false, error: "Contact not found" };

  if (data.jobId) {
    const job = await prisma.job.findFirst({
      where: { id: data.jobId, userId: user.id },
      select: { id: true },
    });
    if (!job) return { ok: false, error: "Job not found" };
  }

  let task: { id: string };
  try {
    task = await prisma.$transaction(async (tx) => {
      await assertCanCreateTask(user.id, tx);
      return tx.followUpTask.create({
        data: {
          userId: user.id,
          contactId: data.contactId,
          jobId: data.jobId || null,
          type: data.type,
          title: data.title,
          messagePreview: data.messagePreview || null,
          dueDate: new Date(data.dueDate),
          channel: data.channel,
          autoGenerated: false,
        },
      });
    });
  } catch (err) {
    if (err instanceof PlanLimitError) return { ok: false, error: err.message };
    throw err;
  }

  revalidatePath("/followups");
  revalidatePath("/dashboard");
  revalidatePath(`/contacts/${data.contactId}`);
  return { ok: true, id: task.id };
}

export async function updateTaskStatus(formData: FormData): Promise<ActionResult> {
  const user = await requireUser();
  const parsed = taskStatusSchema.safeParse(Object.fromEntries(formData));
  if (!parsed.success) return { ok: false, error: "Invalid input" };

  const { taskId, status } = parsed.data;
  const existing = await prisma.followUpTask.findFirst({
    where: { id: taskId, userId: user.id },
  });
  if (!existing) return { ok: false, error: "Task not found" };

  const data: { status: TaskStatus; completedAt?: Date | null } = { status };
  if (status === "DONE" || status === "SENT" || status === "SKIPPED") {
    data.completedAt = new Date();
  } else {
    data.completedAt = null;
  }

  await prisma.followUpTask.update({ where: { id: taskId }, data });

  if (status === "DONE" || status === "SENT") {
    await setMilestoneOnce(user.id, "firstTaskCompletedAt", new Date()).catch(() => {});
  }

  revalidatePath("/followups");
  revalidatePath("/dashboard");
  revalidatePath(`/contacts/${existing.contactId}`);
  return { ok: true };
}

export async function deleteTask(id: string): Promise<ActionResult> {
  const user = await requireUser();
  const existing = await prisma.followUpTask.findFirst({
    where: { id, userId: user.id },
    select: { id: true, contactId: true },
  });
  if (!existing) return { ok: false, error: "Task not found" };

  await prisma.followUpTask.delete({ where: { id } });
  revalidatePath("/followups");
  revalidatePath("/dashboard");
  revalidatePath(`/contacts/${existing.contactId}`);
  return { ok: true };
}

export async function sendTaskEmail(formData: FormData): Promise<ActionResult> {
  const user = await requireUser();
  const parsed = sendEmailSchema.safeParse(Object.fromEntries(formData));
  if (!parsed.success) {
    return { ok: false, error: parsed.error.errors[0]?.message ?? "Invalid input" };
  }
  const { taskId, to, subject, body } = parsed.data;

  const task = await prisma.followUpTask.findFirst({
    where: { id: taskId, userId: user.id },
    include: { contact: true },
  });
  if (!task) return { ok: false, error: "Task not found" };
  if (task.channel !== Channel.EMAIL) {
    return { ok: false, error: "This task is not an email task" };
  }

  const result = await sendEmail({ to, subject, text: body });
  if (!result.ok) return { ok: false, error: result.error };

  await prisma.followUpTask.update({
    where: { id: taskId },
    data: {
      status: TaskStatus.SENT,
      completedAt: new Date(),
      messagePreview: subject,
    },
  });

  await setMilestoneOnce(user.id, "firstTaskCompletedAt", new Date()).catch(() => {});

  revalidatePath("/followups");
  revalidatePath(`/followups/${taskId}`);
  revalidatePath("/dashboard");
  revalidatePath(`/contacts/${task.contactId}`);
  return { ok: true, id: taskId };
}
